set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc" CACHE STRING "")
set(CMAKE_C_CREATE_STATIC_LIBRARY "emcc -o <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "emcc -o <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "")
